name: "New news post"
description: "Create a news post"
title: ""
labels: ["news"]
body:
  - type: input
    id: date
    attributes:
      label: "Date"
      description: "Format: dd-mm-yyyy"
      placeholder: "29-08-2025"
    validations:
      required: true
  - type: input
    id: slug
    attributes:
      label: "Slug"
      description: "Lowercase, hyphens only, ASCII"
      placeholder: "beheading-of-saint-john-the-baptist"
    validations:
      required: true
  - type: dropdown
    id: lang
    attributes:
      label: "Language"
      options: ["sv", "en", "sr"]
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: "Title"
      placeholder: "The Beheading of Saint John the Baptist"
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: "Body"
      description: "Markdown allowed. Drag or paste one or more images below."
      placeholder: "Full text…"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Images: drag or paste below the Body field. They will be handled automatically.
