name: News
description: File a news post (English source; sv/sr come automatically as stubs)
title: "Add Title Here"
labels: ["news"]
assignees: []

body:
  - type: textarea
    id: body
    attributes:
      label: News body (English)
      description: Paste the full text. Quotes, emojis, and line breaks are fine.
      placeholder: Write your news text here...
    validations:
      required: true
