name: "New news post"
description: "Add a news article in any language. Title + Body only."
title: "Add Title"
labels: []
body:
  - type: input
    id: date
    attributes:
      label: "Date"
      description: "Format: dd-mm-yyyy (e.g. 29-08-2025)"
      placeholder: "dd-mm-yyyy"
  - type: dropdown
    id: language
    attributes:
      label: "Language"
      description: "Choose the language for this post."
      options:
        - en
        - sv
        - sr
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: "Body"
      description: "Paste the article text here. You can attach images below; the system will handle variants."
      placeholder: "Write your article text here…"
    validations:
      required: true
