name: "New news post"
description: "Create a news post in one language"
title: "News: <date>-<slug> (<lang>)"
labels: ["news"]
body:
  - type: input
    id: date
    attributes:
      label: "Date"
      description: "Format: dd-mm-yyyy"
      placeholder: "07-11-2025"
    validations:
      required: true

  - type: input
    id: slug
    attributes:
      label: "Slug"
      description: "Lowercase, hyphens only"
      placeholder: "feast-of-archangels"
    validations:
      required: true

  - type: dropdown
    id: lang
    attributes:
      label: "Language"
      options: ["sv", "en", "sr"]
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "Title"
      placeholder: "Ärkeänglarnas fest"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary (1–2 sentences)"
      placeholder: "Kort sammanfattning…"

  - type: textarea
    id: body
    attributes:
      label: "Body"
      description: "Markdown allowed. Paste images directly here."
      placeholder: "Full text…"
    validations:
      required: true

  - type: input
    id: tags
    attributes:
      label: "Tags (comma separated)"
      placeholder: "högtid, ärkeänglar"

  - type: input
    id: cover
    attributes:
      label: "Cover image URL (optional)"
      placeholder: "https://… or leave blank"

  - type: markdown
    attributes:
      value: |
        **Images:** You can drag or paste pictures below the body field. They will be uploaded automatically.
