name: etiquette-thumbs
on:
  push:
    branches:
      - main
    paths:
      - 'assets/img/etiquette/**'
      - '.github/workflows/etiquette-thumbs.yml'
  workflow_dispatch:
jobs:
  thumbs:
    runs-on: ubuntu-latest
    steps:
      - run: echo "etiquette-thumbs workflow active only on main pushes and manual dispatch"
