name: Verify images
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/check-images.sh
